### ISSUE TITLE
request: is code of "Repr Filter" can be open source too?

### ISSUE THREAD

**Issue by Force1ess** [hkust-nlp/deita#2]

**Comment by VPeterV** [comment]
Hi. Thanks for your interest! Yes, we will release the complete pipeline recently and continue to optimize It after this release. Please stay tuned.

**Comment by Force1ess** [comment]
that would be great, thank u for ur replying

**Comment by Force1ess** [comment]
any update? @VPeterV

**Comment by VPeterV** [comment]
Thanks for ur waiting! We are cleaning and refactoring the code. And we plan to release the code this week.
